export * as client from "./client/index.js";
export {
	AuthenticationError,
	AuthorizationError,
	BadRequestError,
	ConflictError,
	ExpectationFailedError,
	FailedDependencyError,
	GoneError,
	LengthRequiredError,
	LockedError,
	MethodNotAllowedError,
	MisdirectedRequestError,
	NotAcceptableError,
	NotFoundError,
	PayloadTooLargeError,
	PaymentRequiredError,
	PreconditionFailedError,
	PreconditionRequiredError,
	ProxyAuthenticationRequiredError,
	RangeNotSatisfiableError,
	RateLimitError,
	RequestHeaderFieldsTooLargeError,
	RequestTimeoutError,
	TooEarlyError,
	UnavailableForLegalReasonsError,
	UnsupportedMediaTypeError,
	UpgradeRequiredError,
	UriTooLongError,
	ValidationError,
} from "./client/index.js";
export * as server from "./server/index.js";

export {
	BadGatewayError,
	GatewayTimeoutError,
	HttpVersionNotSupportedError,
	InsufficientStorageError,
	InternalServerError,
	LoopDetectedError,
	NetworkAuthenticationRequiredError,
	NotExtendedError,
	NotImplementedError,
	ServiceUnavailableError,
	VariantAlsoNegotiatesError,
} from "./server/index.js";
